sonar.projectKey=renata-oliveira_mechanics-software
sonar.organization=renata-oliveira

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/Migrations/**,**/obj/**,**/bin/**,**/Persistence/Seeding/**
sonar.coverage.exclusions=**/Migrations/**,**/obj/**,**/bin/**,**/Persistence/Seeding/**

sonar.cs.opencover.reportsPaths=coverage-results/**/coverage.opencover.xml
