sonar.projectKey=rnataoliveira_mechanics-software
sonar.organization=rnataoliveira

sonar.exclusions=\
  **/Migrations/**,\
  **/obj/**,\
  **/bin/**,\
  **/Persistence/Seeding/**,\
  DELIVERABLES.html,\
  docker-compose*.yml,\
  **/appsettings.Development.json,\
  scripts/**,\
  k8s/secret.yaml,\
  infra/**,\
  .github/workflows/deploy.yml

sonar.coverage.exclusions=\
  **/Migrations/**,\
  **/obj/**,\
  **/bin/**,\
  **/Persistence/Seeding/DatabaseSeeder.cs,\
  **/Program.cs
