sonar.projectKey=rnataoliveira_mechanics-software
sonar.organization=renata-oliveira

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/Migrations/**,**/obj/**,**/bin/**,**/Persistence/Seeding/**,DELIVERABLES.html
sonar.coverage.exclusions=**/Migrations/**,**/obj/**,**/bin/**,**/Persistence/Seeding/DatabaseSeeder.cs

sonar.coverageReportPaths=sonar-coverage/SonarQube.xml
