apiVersion: v1
kind: Service
metadata:
  name: mechanics-software-db
  namespace: mechanics-software
  labels:
    app: mechanics-software
    tier: db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: mechanics-software
    tier: db
